name: Build and Push binary

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/fedora:latest

    steps:
      - name: Install dependencies
        run: dnf install -y git make pkg-config python3 python3-pip patchelf gcc python3-devel gobject-introspection-devel python3-gobject

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install nuitka
        run: python3 -m pip install --upgrade nuitka

      - name: Build pkg
        run: make

      - name: Tell Git the workspace is safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Get short commit SHA and commit count
        id: vars
        run: | 
          echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "commit_number=$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Rename binary
        run: mv ./build/yggui.bin ./build/yggui-x86_64

      - name: Create Pre-release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ steps.vars.outputs.commit_number }}-${{ steps.vars.outputs.short_sha }}
          name: Build from commit ${{ steps.vars.outputs.short_sha }}
          prerelease: true
          generate_release_notes: true
          files: ./build/yggui-x86_64
